name = "Continuations"
uuid = "d9bb2c40-f3fb-4c51-83a6-5d48eba37d78"
authors = ["Mike Innes <mike.j.innes@gmail.com>"]
version = "0.1.0"

[deps]
Libtask = "6f1fad26-d15e-5dc8-ae53-837a1d7b8c9f"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
